%YAML:1.0

#--------------------------------------------------------------------------------------------
# IMU Parameters (fixed).
#--------------------------------------------------------------------------------------------

# IMU data rate
IMU.dps: 185

# Threshold of small angle (<1/2deg)
IMU.nSmallAngle: 0.008726646

# IMU sensor noise
#IMU.sigma_g: 1.6968e-04
#IMU.sigma_wg: 1.9393e-05
#IMU.sigma_a: 2.0000e-3
#IMU.sigma_wa: 3.0000e-3

IMU.sigma_g: 1.6968e-4
IMU.sigma_wg: 1.9393e-3
IMU.sigma_a: 5.0000e-3
IMU.sigma_wa: 2.0000e-3

# Gravity
#IMU.nG: 9.8082
IMU.nG: 10.1

#--------------------------------------------------------------------------------------------
# Camera Parameters (fixed).
#--------------------------------------------------------------------------------------------

# Camera frame rate
Camera.fps: 15

# Is RGB or not
Camera.RGB: 0

# Is fisheye or not
Camera.Fisheye: 0

# Camera image resolution
Camera.width: 960
Camera.height: 540

# Camera intrinsics
Camera.fx: 1067.06
Camera.fy: 1067.81
Camera.cx: 456.07
Camera.cy: 276.98

Camera.k1: -0.344263739
Camera.k2: 0.065336455
Camera.p1: 0
Camera.p2: 0

# Camera image noise (1/f)
Camera.sigma_px: 0.0009
Camera.sigma_py: 0.0009

# Camera extrinsics [B:IMU,C0:cam0]
Camera.T_BC0: !!opencv-matrix
     rows: 4
     cols: 4
     dt: d
     data: [-1.0, 0.0, 0.0, 0.058,
            0.0, 0.0, -1.0, -0.038,
            0.0, -1.0, 0.0, 0.010,
            0.0, 0.0, 0.0, 1.0]
#     data: [ 0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975,
#             0.999557249008, 0.0149672133247, 0.025715529948, -0.064676986768,
#            -0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949,
#             0.0, 0.0, 0.0, 1.0]

# Timeshift of camera to IMU [s] (t_imu=t_cam+shift)
Camera:nTimeOffset: 0

#--------------------------------------------------------------------------------------------
# Tracker Parameters (tunable).
#--------------------------------------------------------------------------------------------

# Number of features per image 
Tracker.nFeatures: 300

# Max. tracking length
Tracker.nMaxTrackingLength: 30

# Min. tracking length
Tracker.nMinTrackingLength: 7

# Min. distance between features
Tracker.nMinDist: 12

# Quality level of features
Tracker.nQualLvl: 0.02

# Size of chess grid
Tracker.nGridSize: 100

# Use histogram equalizer or not
Tracker.EnableEqualizer: 1

# Use Sampson error or not (RANSAC)
Tracker.UseSampson: 1

# Threshold for inlier (RANSAC)
Tracker.nSampsonThrd: 5e-4

#--------------------------------------------------------------------------------------------
# Initialization Parameters (tunable).
#--------------------------------------------------------------------------------------------

# Use initial alignment or not
INI.EnableAlignment: 1

# Time length of initialization [s]
INI.nTimeLength: 3

# Thresholds for moving detection [rad,m]
INI.nThresholdAngle: 0.005
INI.nThresholdDispl: 0.005

# Record the outputs or not
INI.RecordOutputs: 0

#--------------------------------------------------------------------------------------------
# Display Parameters (tunable).
#--------------------------------------------------------------------------------------------

# Size of point
Landmark.nScale: 0.03

# Publishing rate
Landmark.nPubRate: 5
