%YAML:1.0

#--------------------------------------------------------------------------------------------
# IMU Parameters (fixed).
#--------------------------------------------------------------------------------------------

# IMU data rate
IMU.dps: 185

# Threshold of small angle (<1/2deg)
IMU.nSmallAngle: 0.008726646

# IMU sensor noise
IMU.sigma_g: 1.6968e-04
IMU.sigma_wg: 1.9393e-05
IMU.sigma_a: 2.0000e-3
IMU.sigma_wa: 3.0000e-3

# Gravity
IMU.nG: 9.8082

#--------------------------------------------------------------------------------------------
# Camera Parameters (fixed).
#--------------------------------------------------------------------------------------------

# Camera frame rate
Camera.fps: 15

# Camera image resolution
Camera.width: 960
Camera.height: 540

# Camera intrinsics
Camera.fx: 1067.06
Camera.fy: 1067.81
Camera.cx: 456.07
Camera.cy: 276.98

Camera.k1: -0.344263739
Camera.k2: 0.065336455
Camera.p1: 0
Camera.p2: 0
Camera.k3: 0

# Camera extrinsics [B:IMU,C0:cam0]
Camera.T_BC0: !!opencv-matrix
     rows: 4
     cols: 4
     dt: d
     data: [-1.0, 0.0, 0.0, 0.058,
            0.0, 0.0, -1.0, -0.038,
            0.0, -1.0, 0.0, 0.010,
            0.0, 0.0, 0.0, 1.0]

#--------------------------------------------------------------------------------------------
# Feature Parameters (tunable).
#--------------------------------------------------------------------------------------------

# Number of features
Feature.num: 400

# Number of features matching per image 
Feature.thInlier: 5

# Min. feature distance between
Feature.min_px_dist: 7

# Bucket safety region (px)
Bucket.safety: 20

# Bucket size
Bucket.rows: 16
Bucket.cols: 8

#--------------------------------------------------------------------------------------------
# Reconstruction Parameters (tunable).
#--------------------------------------------------------------------------------------------

# Iteration
RANSAC.iterMax: 1e4

# Min. number of samples
RANSAC.nSample: 5

# Inlier ratio
RANSAC.thInlrRatio: 0.9

# Inlier threshold
RANSAC.thDist: 0.5

# Rejection threshold
RANSAC.thDistOut: 5

# Vehicel height
Scale.height: 1.5

# Min. Reprojection error
Scale.error: 1.2

#--------------------------------------------------------------------------------------------
# Display Parameters (tunable).
#--------------------------------------------------------------------------------------------

# Size of point
Landmark.nScale: 0.03

# Publishing rate
Landmark.nPubRate: 5
